home:
    path:     /
    defaults: { _controller: BookkeeperApplicationBundle:Default:index }

book_show:
    path:     /show/{slug}
    defaults: { _controller: "BookkeeperApplicationBundle:Default:show" }
    requirements: { slug: "[a-z-]+" }

book_new:
    path:     /new
    defaults: { _controller: BookkeeperApplicationBundle:Default:new }

book_create:
    path: /create
    defaults: { _controller: "BookkeeperApplicationBundle:Default:create" }
    requirements: { _method: post }

book_edit:
    path: /edit/{slug}
    defaults: { _controller: "BookkeeperApplicationBundle:Default:edit" }
    requirements: { slug: "[a-z-]+" }

book_update:
    path: /update/{slug}
    defaults: { _controller: "BookkeeperApplicationBundle:Default:update" }
    requirements: { slug: "[a-z-]+", _method: put}
