home:
    path:     /
    defaults: { _controller: BookkeeperApplicationBundle:Default:index }

book_show:
    path:     /show/{slug}
    defaults: { _controller: "BookkeeperApplicationBundle:Default:show" }
    requirements: { slug: "[a-z-]+" }
