
services:
    book_model:
        class: Bookkeeper\ApplicationBundle\Model\BookModel
        calls:
            - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]
            - [ setCache, [ "@cache", "%cache%" ] ]
            - [ setPaginator, [ "@knp_paginator" ] ]

    app_mailer:
        class: Bookkeeper\ApplicationBundle\Service\Mailer
        arguments: ['%email%', '@mailer']
