services:
#    bookkeeper_application.example:
#        class: Bookkeeper\ApplicationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    book_model:
        class: Bookkeeper\ApplicationBundle\Model\BookModel
        arguments: ['@service_container']
