book_new:
    path:     /new
    defaults: { _controller: BookkeeperManagerBundle:Book:new }

book_create:
    path: /create
    defaults: { _controller: "BookkeeperManagerBundle:Book:create" }
    requirements: { _method: post }

book_edit:
    path: /edit/{slug}
    defaults: { _controller: "BookkeeperManagerBundle:Book:edit" }
    requirements: { slug: "[a-z-]+" }

book_update:
    path: /update/{slug}
    defaults: { _controller: "BookkeeperManagerBundle:Book:update" }
    requirements: { slug: "[a-z-]+", _method: put}

book_delete:
    path: /delete/{slug}
    defaults: { _controller: "BookkeeperManagerBundle:Book:delete" }
    requirements: { _method: delete, slug: "[a-z-]+" }

