book_new:
    path:     /new
    defaults: { _controller: "BookkeeperManagerBundle:Book:new" }
    methods: [GET]

book_create:
    path: /create
    defaults: { _controller: "BookkeeperManagerBundle:Book:create" }
    methods: [POST]

book_edit:
    path: /edit/{slug}
    defaults: { _controller: "BookkeeperManagerBundle:Book:edit" }
    methods: [GET]
    requirements: { slug: "[a-z-]+" }

book_update:
    path: /update/{slug}
    defaults: { _controller: "BookkeeperManagerBundle:Book:update" }
    methods: [PUT]
    requirements: { slug: "[a-z-]+" }

book_delete:
    path: /delete/{slug}
    defaults: { _controller: "BookkeeperManagerBundle:Book:delete" }
    methods: [DELETE]
    requirements: { slug: "[a-z-]+" }

