security:
    providers:
        administrators:
            entity: { class: BookkeeperUserBundle:User, property: username }

    encoders:
        Bookkeeper\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /login
            remember_me:
                key: "%secret%"
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/new, roles: ROLE_ADMIN }
        - { path: ^/create, roles: ROLE_ADMIN }
        - { path: ^/edit, roles: ROLE_ADMIN }
        - { path: ^/update, roles: ROLE_ADMIN }
        - { path: ^/delete, roles: ROLE_ADMIN }
