security:
    providers:
        administrators:
            entity: { class: BookkeeperApplicationBundle:User, property: username }

    encoders:
        Bookkeeper\ApplicationBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /login

    access_control:
        # require ROLE_ADMIN for /admin
        - { path: ^/admin, roles: ROLE_ADMIN }
