login:
    path:     /login
    defaults: { _controller: BookkeeperUserBundle:Default:login }

login_check:
    path: /login_check

logout:
    path:     /logout

signup:
    path: /signup
    defaults: { _controller: "BookkeeperUserBundle:User:SignUp" }
