
services:
    user_model:
        class: Bookkeeper\UserBundle\Model\UserModel
        arguments: ['@service_container']

    access_listener:
        class: Bookkeeper\UserBundle\Security\AccessListener
        arguments: [ @security.token_storage, @security.authorization_checker, @router ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
